### ISSUE TITLE
FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24.

### ISSUE THREAD

**Issue by dburkhardt** [brianhie/geosketch#11]
```
/usr/lib/python3.8/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
```

Affects https://github.com/brianhie/geosketch/blob/ec93a46654adc161e40ba5329c232b17a92adf68/geosketch/kmeanspp.py

I would fix, but since you import `*` it's hard to know exactly what's coming from that module.

**Comment by brianhie** [comment]
Thanks @dburkhardt -- is this a separate issue from https://github.com/brianhie/geosketch/pull/10? This PR should be reflected in the most recent release, but let me know if you're still seeing the issue with v1.2.

**Comment by dburkhardt** [comment]
Oh no, it looks like it's the same. I had looked for a closed issue about it, but couldn't find it. I didn't realize I wasn't using the most recent version from pypi. I had 1.1 installed 🤦‍♂️. I've upgraded to 1.2 and it's fixed!
