### ISSUE TITLE
Pandas DataFrame as input

### ISSUE THREAD

**Issue by adamov-artem** [brianhie/geosketch#3]
Hi. Is it possible to run geosketch on a DataFrame object? I need to save row- and colnames of my count matrix.

**Comment by brianhie** [comment]
@adamov-artem you can call [`to_numpy()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html) to get the count matrix, then do the PCA/geosketch routine, and then use the indices returned by `gs()` to index into your data frame using [`iloc()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc).

For example, 
```
X = data_frame.to_numpy()

# PCA.
from fbpca import pca
U, s, Vt = pca(X, k=100) # E.g., 100 PCs.
X_dimred = U[:, :100] * s[:100]

# Sketch.
from geosketch import gs
N = 20000 # Number of samples to obtain from the data set.
sketch_index = gs(X_dimred, N, replace=False)

data_frame_sketch = data_frame.iloc[sketch_index, :]
```
