### ISSUE TITLE
Label count mismatch

### ISSUE THREAD

**Issue by wsnoble** [brianhie/geosketch#5]
I am seeing a mismatch between the count of rarest cell type reported in the paper and the one in the data tar file. The paper says

"In particular, we focused on 28 293T cells (0.66% of the total number of cells in the dataset) in the 293T/Jurkat mixture, 262 dendritic cells (0.38%) in the PBMC dataset, 1,695 macrophages (0.25%) among the adult mouse brain cells, and 2,777 ependymal cells (0.60%) among the mouse CNS cells." 

 I changed into the data/geosketch/cell_labels directory and had no problem verifying the numbers for the first two data sets:

bash-4.1$ grep 293t jurkat_293t_99_1_clusters.txt | wc -l
28
bash-4.1$ grep Dendritic pbmc_68k_cluster.txt | wc -l
262

However, for the second two data set the numbers do not agree. For mouse brain (Saunders) we get 1866 macrophages instead of the expected 1695:

bash-4.1$ grep Macrophage mouse_brain_cluster.txt | wc -l
1866
      

For the mouse CNS cells (Zeisel) we get 2974 instead of the expected 2777:

bash-4.1$ grep Ependymal zeisel_cluster.txt | wc -l
2974
    
Are the numbers in the paper incorrect?

**Comment by brianhie** [comment]
The analysis does some additional cell filtering once the data has been loaded from disk.

The Saunders analysis filters out cells labeled as "doublet" and "outlier" provided by the original study (https://github.com/brianhie/geosketch/blob/master/bin/mouse_brain.py#L69) and the Zeisel analysis filters out low quality/transcriptionally quiescent cells (https://github.com/brianhie/geosketch/blob/master/bin/zeisel.py#L43). We reported cell counts after quality filtering.

That should give you the right number, but let us know if you still see a discrepancy and we can try to figure it out.
