### ISSUE TITLE
Not really the rarest cell types?

### ISSUE THREAD

**Issue by wsnoble** [brianhie/geosketch#7]
I am looking at the data underlying Figure 2C, and I noticed that for the adult mouse brain data set, the macrophages are not actually the rarest cell type. They are something like the third-most rare cell type. Is there a reason you focused on this particular cell type for that data set, rather than the mitotic cells?

**Comment by brianhie** [comment]
I believe there were some unlabeled cells and cells labeled as "mitotic," which isn't really a cell type but rather cells with a high level of cell cycle-related genes for which the cell type couldn't be assigned. So "macrophage" was the rarest label that corresponds to what is usually thought of as a "cell type."

**Comment by wsnoble** [comment]
Ah right! Makes sense. Thanks!
