### ISSUE TITLE
Index issue of the R wrapper

### ISSUE THREAD

**Issue by KevinBastianYang** [brianhie/geosketch#8]
Hi,

I think this is a great method and I try to use it in my project.

 But when I ran the codes from example.R file, I noticed that `sketch.indices` can start from 0 and end at 999 (if there are 1000 cells in total). I guess this is because it uses reticulate to call the python codes which start from 0. 

I wonder whether this is designed on purpose or not. I think many R users will think the index starts from 1 by default, but if they use these indices directly for indexing matrices, completely different cells will be chosen.

**Comment by brianhie** [comment]
That is a great point! I modified the README with a warning for R users: https://github.com/brianhie/geosketch/commit/8b7f93acdfa5b3d4fde68840489ac9b292ba14ec

It's a Python-first package, but I could add an option that returns a 1-indexed result.

**Comment by brianhie** [comment]
Ok, I've modified the script to be able to return 1-indexed results and updated `example.R` with a warning comment and `one_indexed=TRUE`: https://github.com/brianhie/geosketch/commit/65f519b30e836fb8a3456a59734bf0347380fc0b

Hopefully this should help R users!
