### ISSUE TITLE
How could results of geosketch be replicatable?

### ISSUE THREAD

**Issue by IMJoeyZhu** [brianhie/geosketch#9]
Hey there,

I'm trying to generate identical results by using `geosketch`. But it seems that the result is hard to be replicated. I used `set.seed()` but it did not work. How could I make it?

Joey

**Comment by brianhie** [comment]
Hi @IMJoeyZhu, could you try the `sketch` parameter? https://github.com/brianhie/geosketch/blob/7a669395fcf161bd6a89b61db09570f9863b6a5c/geosketch/sketch.py#L17

That just sets the numpy seed and worked for us to ensure reproducibility.

Closing for now but feel free to reopen if there's a bug.
